apiVersion: v1
kind: Service
metadata:
  name: {{ include "oopsy.fullname" . }}
  labels:
    {{- include "oopsy.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    kind: web
    {{- include "oopsy.selectorLabels" . | nindent 4 }}
