require: standard

inherit_gem:
  standard: config/base.yml

AllCops:
  SuggestExtensions: false
  Exclude:
    - db/schema.rb

Layout/ExtraSpacing:
  AllowForAlignment: true

Layout/HashAlignment:
  EnforcedColonStyle: table
  EnforcedHashRocketStyle: table
